version: '3.8'

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud-test
    ports:
      - "8080:80"
    volumes:
      - nextcloud_data:/var/www/html
      - ./:/var/www/html/custom_apps/rybbit_tracking
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin123
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: nextcloud-db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
    volumes:
      - db_data:/var/lib/mysql

volumes:
  nextcloud_data:
  db_data:
